/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import ArayuzIslemleri.ColorAndIcons;
import ArayuzIslemleri.GirisEkranIslemleri;
import Kullanıcılar.Kullanıcı;
import MailConfig.MailIslemleri;
import SQLIslemleri.SQLKullaniciIslemleri;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

public class GirisEkrani extends javax.swing.JFrame {
    
    private String DB_KULLANICI = "kullanıcılar";
    
    //class
    ColorAndIcons colorAndIcons = new ColorAndIcons();
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    MailIslemleri mail = new MailIslemleri();
    SQLKullaniciIslemleri sqlKullaniciIslemleri = new SQLKullaniciIslemleri(mail, DB_KULLANICI);
    GirisEkranIslemleri girisEkran;
    
    //methods
    public Integer posX;
    public Integer posY;
    private boolean sifreKurtarmaIslemi;
    
    private boolean sayacDurdur = false;
    private boolean sifreSonuc = false;
    
    
    public GirisEkrani() {
        initComponents();
        initComponents2(false);
        
        jTextField_KullanıcıAdı.setText("emre");
        jPasswordField_sifre.setText(new String("12345"));
        
        this.setLocation(dim.width/2 - this.getSize().width/2,dim.height/2 -this.getSize().height/2 );
    }
    public void initComponents2(boolean basta){
        jLabel_KurtarmaMesaji.setVisible(basta);
        jLabel_Sayac.setVisible(basta);
        jTextField_KurtarmaKodu.setVisible(basta);
        
        jTextField_KullanıcıAdı.setVisible(!basta);
        jPasswordField_sifre.setVisible(!basta);
        jLabel_SifremiUnuttum.setVisible(!basta);
        
        if(basta){
            jLabel_UserLogin.setIcon(colorAndIcons.getUser2());
        }else{
            jLabel_UserLogin.setIcon(colorAndIcons.getUser());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_MainPanel = new javax.swing.JPanel();
        jPanel_GirisIcon = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_GirisParametreleri = new javax.swing.JPanel();
        jPanel_Navigation = new javax.swing.JPanel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel_Minimize = new javax.swing.JLabel();
        jLabel_Move = new javax.swing.JLabel();
        jPanel_KullanıcıIcon = new javax.swing.JPanel();
        jLabel_UserLogin = new javax.swing.JLabel();
        jLabel_KurtarmaMesaji = new javax.swing.JLabel();
        jLabel_Sayac = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField_KullanıcıAdı = new javax.swing.JTextField();
        jPasswordField_sifre = new javax.swing.JPasswordField();
        jTextField_KurtarmaKodu = new javax.swing.JTextField();
        jLabel_SifremiUnuttum = new javax.swing.JLabel();
        jButton_GirisYap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel_MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel_GirisIcon.setPreferredSize(new java.awt.Dimension(306, 432));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/company2.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(306, 432));

        javax.swing.GroupLayout jPanel_GirisIconLayout = new javax.swing.GroupLayout(jPanel_GirisIcon);
        jPanel_GirisIcon.setLayout(jPanel_GirisIconLayout);
        jPanel_GirisIconLayout.setHorizontalGroup(
            jPanel_GirisIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_GirisIconLayout.setVerticalGroup(
            jPanel_GirisIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );

        jPanel_GirisParametreleri.setBackground(new java.awt.Color(255, 255, 255));

        jPanel_Navigation.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseExited(evt);
            }
        });

        jLabel_Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        jLabel_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseExited(evt);
            }
        });

        jLabel_Move.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Move.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/move.png"))); // NOI18N
        jLabel_Move.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel_MoveMouseDragged(evt);
            }
        });
        jLabel_Move.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MoveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MoveMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_MoveMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_NavigationLayout = new javax.swing.GroupLayout(jPanel_Navigation);
        jPanel_Navigation.setLayout(jPanel_NavigationLayout);
        jPanel_NavigationLayout.setHorizontalGroup(
            jPanel_NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Move, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Minimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Close)
                .addGap(10, 10, 10))
        );
        jPanel_NavigationLayout.setVerticalGroup(
            jPanel_NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NavigationLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel_NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Minimize)
                    .addComponent(jLabel_Close))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_NavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Move, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_KullanıcıIcon.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_UserLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_UserLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_KullanıcıIconLayout = new javax.swing.GroupLayout(jPanel_KullanıcıIcon);
        jPanel_KullanıcıIcon.setLayout(jPanel_KullanıcıIconLayout);
        jPanel_KullanıcıIconLayout.setHorizontalGroup(
            jPanel_KullanıcıIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_UserLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_KullanıcıIconLayout.setVerticalGroup(
            jPanel_KullanıcıIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_UserLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel_KurtarmaMesaji.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_KurtarmaMesaji.setForeground(new java.awt.Color(32, 188, 233));
        jLabel_KurtarmaMesaji.setText("Kurtarma Kodunu Giriniz :");

        jLabel_Sayac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Sayac.setForeground(new java.awt.Color(32, 188, 233));
        jLabel_Sayac.setText("120");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField_KullanıcıAdı.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextField_KullanıcıAdı.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Kullanıcı Adı ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Gill Sans MT", 1, 14))); // NOI18N
        jTextField_KullanıcıAdı.setMinimumSize(new java.awt.Dimension(64, 40));
        jTextField_KullanıcıAdı.setPreferredSize(new java.awt.Dimension(64, 40));
        jTextField_KullanıcıAdı.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_KullanıcıAdıKeyPressed(evt);
            }
        });

        jPasswordField_sifre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sifre ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Gill Sans MT", 1, 14))); // NOI18N
        jPasswordField_sifre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_sifreKeyPressed(evt);
            }
        });

        jTextField_KurtarmaKodu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Kurtarma Kodu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Gill Sans MT", 1, 14))); // NOI18N
        jTextField_KurtarmaKodu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_KurtarmaKoduKeyPressed(evt);
            }
        });

        jLabel_SifremiUnuttum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_SifremiUnuttum.setForeground(new java.awt.Color(51, 51, 255));
        jLabel_SifremiUnuttum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_SifremiUnuttum.setText("Şifremi Unuttum");
        jLabel_SifremiUnuttum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_SifremiUnuttumMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_SifremiUnuttumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_SifremiUnuttumMouseExited(evt);
            }
        });

        jButton_GirisYap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png"))); // NOI18N
        jButton_GirisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GirisYapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField_sifre, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField_KurtarmaKodu, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel_SifremiUnuttum, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_GirisYap, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField_KullanıcıAdı, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTextField_KullanıcıAdı, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_KurtarmaKodu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_SifremiUnuttum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_GirisYap)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel_GirisParametreleriLayout = new javax.swing.GroupLayout(jPanel_GirisParametreleri);
        jPanel_GirisParametreleri.setLayout(jPanel_GirisParametreleriLayout);
        jPanel_GirisParametreleriLayout.setHorizontalGroup(
            jPanel_GirisParametreleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Navigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_KullanıcıIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_GirisParametreleriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_KurtarmaMesaji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Sayac, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_GirisParametreleriLayout.setVerticalGroup(
            jPanel_GirisParametreleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_GirisParametreleriLayout.createSequentialGroup()
                .addComponent(jPanel_Navigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_KullanıcıIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel_GirisParametreleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_KurtarmaMesaji)
                    .addComponent(jLabel_Sayac))
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_MainPanelLayout = new javax.swing.GroupLayout(jPanel_MainPanel);
        jPanel_MainPanel.setLayout(jPanel_MainPanelLayout);
        jPanel_MainPanelLayout.setHorizontalGroup(
            jPanel_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MainPanelLayout.createSequentialGroup()
                .addComponent(jPanel_GirisIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_GirisParametreleri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_MainPanelLayout.setVerticalGroup(
            jPanel_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_GirisIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
            .addComponent(jPanel_GirisParametreleri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseEntered
        
        jLabel_Minimize.setIcon(colorAndIcons.getMinimize2());
        
    }//GEN-LAST:event_jLabel_MinimizeMouseEntered

    private void jLabel_MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseExited
        jLabel_Minimize.setIcon(colorAndIcons.getMinimize());
    }//GEN-LAST:event_jLabel_MinimizeMouseExited

    private void jLabel_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseEntered
        jLabel_Close.setIcon(colorAndIcons.getCancel2());
    }//GEN-LAST:event_jLabel_CloseMouseEntered

    private void jLabel_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseExited
        jLabel_Close.setIcon(colorAndIcons.getCancel());
    }//GEN-LAST:event_jLabel_CloseMouseExited

    private void jLabel_MoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MoveMouseEntered
        jLabel_Move.setIcon(colorAndIcons.getMove2());
    }//GEN-LAST:event_jLabel_MoveMouseEntered

    private void jLabel_MoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MoveMouseExited
        jLabel_Move.setIcon(colorAndIcons.getMove());
    }//GEN-LAST:event_jLabel_MoveMouseExited

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jLabel_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel_MinimizeMouseClicked

    private void jLabel_MoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MoveMouseClicked
        
    }//GEN-LAST:event_jLabel_MoveMouseClicked

    private void jLabel_SifremiUnuttumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SifremiUnuttumMouseEntered
        jLabel_SifremiUnuttum.setForeground(Color.BLACK);
        jLabel_SifremiUnuttum.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel_SifremiUnuttumMouseEntered

    private void jLabel_SifremiUnuttumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SifremiUnuttumMouseExited
        jLabel_SifremiUnuttum.setForeground(colorAndIcons.getMavi());
        jLabel_SifremiUnuttum.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel_SifremiUnuttumMouseExited

    private void jLabel_SifremiUnuttumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SifremiUnuttumMouseClicked
        
        String girilenkullaniciAdi = jTextField_KullanıcıAdı.getText();
        girilenkullaniciAdi = girilenkullaniciAdi.replaceAll(" ","" );
        jTextField_KullanıcıAdı.setText(girilenkullaniciAdi);
        
        Kullanıcı kullanıcı;
        boolean mailAdresiBulunduMu = false;
        
        if(!girilenkullaniciAdi.equals("")){ //send mail
            int dialogButton = JOptionPane.showConfirmDialog(this, "Kurtarma Kodu Mailinize Gönderilsin mi?","Uyarı",JOptionPane.YES_NO_OPTION);
            
            if(dialogButton == 0){ //yes
                
                try {
                    kullanıcı = sqlKullaniciIslemleri.kullanıcıBul(girilenkullaniciAdi);
                    
                    if(kullanıcı == null){
                        throw new NullPointerException();
                    }else{
                        initComponents2(true);
                        
                        mailAdresiBulunduMu = sqlKullaniciIslemleri.sifremiUnuttum(kullanıcı);
                        
                    //check True or false.
                    
                    SwingWorker<Boolean, Integer> worker = new SwingWorker<Boolean, Integer>() {
                    @Override
                    protected Boolean doInBackground() throws Exception {
                        
                        for(int i=120;i>=0;i--){
                            if(!sifreSonuc){
                                jLabel_Sayac.setText(String.valueOf(i));
                                Thread.sleep(1000); 
                            }else{
                                sayacDurdur = true;
                                return true;
                            }
                        }
                        return true;
                    }

                    @Override
                    protected void done() {
                        initComponents2(false);
                        
                        if(!sayacDurdur){
                            JOptionPane.showMessageDialog(GirisEkrani.this, "Süreniz Bitti");
                        }else{
                            JOptionPane.showMessageDialog(GirisEkrani.this, "Kullanıcı Şifreniz: " +kullanıcı.getKullanıcıSifre());
                            jPasswordField_sifre.setText(kullanıcı.getKullanıcıSifre());
                        }
                    }
                };
                worker.execute();
                }
                    
                    
                } catch (MessagingException | SQLException ex) {
                    Logger.getLogger(GirisEkrani.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NullPointerException ex){
                    JOptionPane.showMessageDialog(this, "Girilen Kullanıcı Adı İle Kullanıcı Bulunamadı");
                }
                
                
            }
            
        }else{
            JOptionPane.showMessageDialog(this, "Lütfen Kullanıcı Adı Giriniz!");
        }
        
    }//GEN-LAST:event_jLabel_SifremiUnuttumMouseClicked

    private void jLabel_MoveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MoveMousePressed
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_jLabel_MoveMousePressed

    private void jLabel_MoveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MoveMouseDragged
        this.setLocation(evt.getXOnScreen()-posX-311, evt.getYOnScreen()-posY-7);
    }//GEN-LAST:event_jLabel_MoveMouseDragged

    private void jButton_GirisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GirisYapActionPerformed
        
                      
        this.sifreKurtarmaIslemi = jTextField_KurtarmaKodu.isVisible();  
        girisEkran = new GirisEkranIslemleri(jTextField_KullanıcıAdı, jTextField_KurtarmaKodu, jPasswordField_sifre);
        
        String girilenKullanıcıAdı = jTextField_KullanıcıAdı.getText();
        String girilenKullanıcıSifre = new String(jPasswordField_sifre.getPassword());
                
        boolean girisSonuc = false;
        boolean sifreSonuc = false;
        
        Kullanıcı kullanıcı;
                
        if(!sifreKurtarmaIslemi){  
                        
            try {
                girisSonuc = girisEkran.bosGirisKontrol();
                
                if(girisSonuc){
                    kullanıcı = sqlKullaniciIslemleri.kullaniciBul(girilenKullanıcıAdı, girilenKullanıcıSifre);
                    
                    if(kullanıcı == null){
                        throw new NullPointerException();
                    }else{
                        this.setVisible(false);
                        SVSUI svsui = new SVSUI(kullanıcı);
                        svsui.setVisible(true);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, girisEkran.getSonucMesaj());
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(GirisEkrani.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NullPointerException ex){
                JOptionPane.showMessageDialog(this, "Hatalı Kullanıcı Adı veya Şifresi Girdiniz");
            }
                   
            
        }else{  // Şifre Kurtarma işlemi yapıyorum
        
            sifreSonuc = girisEkran.sifreKurtar(mail.getSifreKurtarmaKodu());            
            
            if(sifreSonuc){
                
                this.sifreSonuc = true;
            }else{
            
                JOptionPane.showMessageDialog(this, girisEkran.getSonucMesaj());
            }
            
        }
        
    }//GEN-LAST:event_jButton_GirisYapActionPerformed

    private void jTextField_KullanıcıAdıKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_KullanıcıAdıKeyPressed
        
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            jButton_GirisYap.doClick();
        }
        
    }//GEN-LAST:event_jTextField_KullanıcıAdıKeyPressed

    private void jPasswordField_sifreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_sifreKeyPressed
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            jButton_GirisYap.doClick();
        }
    }//GEN-LAST:event_jPasswordField_sifreKeyPressed

    private void jTextField_KurtarmaKoduKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_KurtarmaKoduKeyPressed
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            jButton_GirisYap.doClick();
        }
    }//GEN-LAST:event_jTextField_KurtarmaKoduKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkrani().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_GirisYap;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_KurtarmaMesaji;
    private javax.swing.JLabel jLabel_Minimize;
    private javax.swing.JLabel jLabel_Move;
    private javax.swing.JLabel jLabel_Sayac;
    private javax.swing.JLabel jLabel_SifremiUnuttum;
    private javax.swing.JLabel jLabel_UserLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_GirisIcon;
    private javax.swing.JPanel jPanel_GirisParametreleri;
    private javax.swing.JPanel jPanel_KullanıcıIcon;
    private javax.swing.JPanel jPanel_MainPanel;
    private javax.swing.JPanel jPanel_Navigation;
    private javax.swing.JPasswordField jPasswordField_sifre;
    private javax.swing.JTextField jTextField_KullanıcıAdı;
    private javax.swing.JTextField jTextField_KurtarmaKodu;
    // End of variables declaration//GEN-END:variables
}
